caption: Set the default policy value for <ph name="PRODUCT_NAME">$1<ex>Google Chrome</ex></ph>'s covered generative AI features

desc: |-
  This policy defines the default setting for all covered generative AI features. For example, if this policy is set to value 1, then 1 will be the default setting for all covered generative AI features. It will not impact any manually set policy values. This setting will define the defaults for covered generative AI features in Chrome. See https://support.google.com/chrome/a?p=generative_ai_settings for the list of covered features.

  Some policies, e.g. <ph name="GEMINI_SETTINGS_POLICY_NAME">GeminiSettings</ph>, only support the states Allowed and Do not allow. In this case, if <ph name="GEN_AI_DEFAULT_SETTINGS_POLICY_NAME">GenAiDefaultSettings</ph> is set to 0 or 1, this feature will be enabled. If <ph name="GEN_AI_DEFAULT_SETTINGS_POLICY_NAME">GenAiDefaultSettings</ph> is set to 2, this feature will be disabled. The documentation for each feature contains more details about how it interacts with values in this policy (e.g. Gemini in Chrome - https://support.google.com/chrome/a/?p=gemini_in_chrome). This applies to the following features: Gemini in Chrome, Google Lens, and AI Mode as they are subject to their own guarantees and/or terms of service (https://support.google.com/chrome/a/?p=genai_features_chrome).

  0 = Allow the feature to be used, while allowing Google to use relevant data to improve its AI models. Relevant data may include prompts, inputs, outputs, source materials, and written feedback, depending on the feature. It may also be reviewed by humans to improve AI models. 0 is the default value, except when noted below.

  1 = Allow the feature to be used, but does not allow Google to improve models using users' content (including prompts, inputs, outputs, source materials, and written feedback). 1 is the default value for Enterprise users managed by <ph name="GOOGLE_ADMIN_CONSOLE_PRODUCT_NAME">Google Admin console</ph> and for Education accounts managed by <ph name="GOOGLE_WORKSPACE_PRODUCT_NAME">Google Workspace</ph>.

  2 = Do not allow the feature.

  For more information on data handling for generative AI features, please see https://support.google.com/chrome/a?p=generative_ai_settings.

default: 0
default_for_enterprise_users: 1
example_value: 2
features:
  cloud_only: true
  dynamic_refresh: true
  per_profile: true
future_on:
- fuchsia
items:
- caption: Allow GenAI features and improve AI models
  name: Allowed
  value: 0
- caption: Allow GenAI features without improving AI models
  name: AllowedWithoutLogging
  value: 1
- caption: Do not allow GenAI features
  name: Disabled
  value: 2
owners:
- igorruvinov@chromium.org
- file://components/policy/OWNERS
# LINT.IfChange
schema:
  enum:
  - 0
  - 1
  - 2
  type: integer
# LINT.ThenChange(//components/policy/core/browser/gen_ai_default_settings_policy_handler.cc, //chrome/browser/policy/configuration_policy_handler_list_factory.cc)
supported_on:
- android:130-
- chrome.*:130-
- chrome_os:130-
- ios:130-
tags: []
type: int-enum
